services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - backend
        environment:
            - NEXT_PUBLIC_API_URL=http://localhost:4000
        networks:
            - app-network
        develop:
            watch:
                - action: sync
                  path: ./frontend
                  target: /app
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: package.json

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
            - "4001:4001"
        depends_on:
            - mongo
            - rabbitmq
        environment:
            - DATABASE_URL=mongodb://mongo:27017/you_app
            - RABBITMQ_URL=amqp://rabbitmq
            - JWT_SECRET=abela-a@youapp
            - JWT_REFRESH_SECRET=abelardhana@youapp
            - JWT_EXPIRATION=15m
            - JWT_REFRESH_EXPIRATION=1d
            - SOCKET_PORT=4001
        networks:
            - app-network
        develop:
            watch:
                - action: sync
                  path: ./backend
                  target: /app
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: package.json

    mongo:
        image: mongo:latest
        container_name: mongo
        ports:
            - "27017:27017"
        networks:
            - app-network

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
